"""IR encoder: compile a .crit file and emit critter_ir.h.

First-cut encoder per HAL_SPEC Phase 1A. The spec ultimately wants string
opcodes rewritten into a tagged-union table; we keep strings intact for now
and let the C++ interpreter string-match. Switch to the opcode table when
the interpreter lands — no point bikeshedding it before the consumer exists.

Usage:
    python3 hal/ir/ir_encoder.py <path>.crit [-o critter_ir.h]
"""

import argparse
import os
import sys
import textwrap

# Make the repo root importable regardless of cwd.
_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from compiler import CritCompiler  # noqa: E402


def _c_str(s):
    """Escape a Python string for use as a C string literal."""
    out = []
    for ch in s:
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif ch == '\n':
            out.append('\\n')
        elif ch == '\t':
            out.append('\\t')
        elif 0x20 <= ord(ch) < 0x7f:
            out.append(ch)
        else:
            out.append(f'\\x{ord(ch):02x}')
    return '"' + ''.join(out) + '"'


def _c_ident(s):
    """Sanitize a name into a C identifier fragment."""
    return ''.join(c if c.isalnum() else '_' for c in s)


def encode(ir, source_path, width, height):
    lines = []
    emit = lines.append

    emit("// Auto-generated by hal/ir/ir_encoder.py. Do not edit by hand.")
    emit(f"// Source: {os.path.basename(source_path)}")
    emit("#pragma once")
    emit("#include <cstdint>")
    emit("")
    # Grid geometry. Emitted here (rather than only in the device header)
    # because CritterEngine.cpp doesn't see creds.h — without these defines,
    # the engine TU compiles against CritterEngine.h's 16x16 fallback and
    # only paints the top-left quadrant of a non-square panel. Guarded with
    # #ifndef so host builds passing -DGRID_WIDTH/-DGRID_HEIGHT still win.
    emit(f"#ifndef GRID_WIDTH")
    emit(f"#define GRID_WIDTH {width}")
    emit(f"#endif")
    emit(f"#ifndef GRID_HEIGHT")
    emit(f"#define GRID_HEIGHT {height}")
    emit(f"#endif")
    emit("")
    emit("namespace critter_ir {")
    emit("")

    # --- version + simulation ---
    emit(f"constexpr uint8_t IR_VERSION = {ir['ir_version']};")
    emit(f"constexpr uint32_t TICK_RATE_MS = {ir['simulation']['tick_rate']};")
    emit("")

    # --- structs ---
    emit(textwrap.dedent("""\
        struct CycleEntry { uint8_t color_idx; uint8_t frames; };
        // kind: 0 = static RGB; 1 = cycle (walks CYCLE_ENTRIES[cycle_start ..
        // cycle_start+cycle_count) using a render-frame counter). For static
        // colors the r/g/b fields are authoritative; for cycle colors they
        // hold the first entry's resolved RGB as a fallback when the cycle
        // table is empty (shouldn't happen — encoder rejects empty cycles).
        struct Color     { const char* name; uint8_t kind;
                           uint8_t r, g, b;
                           uint8_t cycle_start, cycle_count; };
        struct Point     { int8_t x, y; };
        struct Landmark  { const char* name; const char* color;
                           const Point* points; uint16_t point_count; };
        struct AgentType { const char* name; uint16_t limit;
                           const char* const* states; uint16_t state_count; };
        struct InitialAgent { const char* name; int8_t x, y; const char* state; };
        struct SpawnRule { const char* agent_type; const char* landmark;
                           uint32_t interval; const char* condition; };
        struct PFConfig  { const char* agent_name;
                           int32_t max_nodes;
                           int32_t penalty_lit;
                           int32_t penalty_occupied;
                           uint8_t diagonal;          // 0/1
                           float   diagonal_cost;     // ignored if !diagonal
                           int32_t step_rate;
                           uint8_t has_max_nodes, has_penalty_lit,
                                   has_penalty_occupied, has_diagonal,
                                   has_diagonal_cost, has_step_rate; };
        struct Insn      { uint8_t indent; const char* text; };
        struct Behavior  { const char* agent_name;
                           const Insn* insns; uint16_t insn_count; };
        """))

    # --- colors ---
    #
    # Two-pass layout: first assign each color a stable index (matches the
    # order in ir["colors"]), then flatten cycles into CYCLE_ENTRIES so that
    # cycle-entry color refs resolve to indices, not strings. The C++ engine
    # walks cycles by frame counter and indexes straight into COLORS — no
    # runtime name lookup on the hot path.
    colors = ir.get("colors", {})
    color_idx = {name: i for i, name in enumerate(colors.keys())}

    def _resolve_static(name, depth=0):
        """Resolve a name to a literal (r,g,b), chasing cycles to their first
        entry. Used as the Color.r/g/b fallback for cycle entries so a broken
        table still produces something non-black."""
        if depth > 4:
            return (255, 255, 255)
        d = colors.get(name)
        if d is None:
            return (255, 255, 255)
        if isinstance(d, tuple) or isinstance(d, list):
            return tuple(d)
        if isinstance(d, dict) and d.get("kind") == "cycle":
            entries = d.get("entries", [])
            if not entries:
                return (255, 255, 255)
            return _resolve_static(entries[0][0], depth + 1)
        return (255, 255, 255)

    cycle_entries = []  # flat list of (color_idx, frames)
    cycle_ranges = {}   # name -> (start, count)
    for name, d in colors.items():
        if isinstance(d, dict) and d.get("kind") == "cycle":
            entries = d.get("entries", [])
            if not entries:
                raise ValueError(f"Color '{name}' has an empty cycle.")
            start = len(cycle_entries)
            for sub_name, frames in entries:
                if sub_name not in color_idx:
                    raise ValueError(
                        f"Cycle color '{name}' references unknown color "
                        f"'{sub_name}'.")
                cycle_entries.append((color_idx[sub_name], int(frames)))
            cycle_ranges[name] = (start, len(entries))

    emit("constexpr CycleEntry CYCLE_ENTRIES[] = {")
    for (ci, fr) in cycle_entries:
        emit(f"  {{ {ci}, {fr} }},")
    # Trailing zero so the array is non-empty even if no cycles are defined
    # (C++ forbids zero-size arrays in some modes and ODR-uses constexpr).
    if not cycle_entries:
        emit("  { 0, 0 },")
    emit("};")
    emit("")

    emit(f"constexpr Color COLORS[] = {{")
    for name, d in colors.items():
        r, g, b = _resolve_static(name)
        if isinstance(d, dict) and d.get("kind") == "cycle":
            start, count = cycle_ranges[name]
            emit(f"  {{ {_c_str(name)}, 1, {r}, {g}, {b}, {start}, {count} }},")
        else:
            emit(f"  {{ {_c_str(name)}, 0, {r}, {g}, {b}, 0, 0 }},")
    emit("};")
    emit(f"constexpr uint16_t COLOR_COUNT = {len(colors)};")
    emit("")

    # --- landmarks ---
    landmarks = ir.get("landmarks", {})
    for name, lm in landmarks.items():
        ident = _c_ident(name)
        pts = lm.get("points", [])
        emit(f"constexpr Point LANDMARK_PTS_{ident}[] = {{")
        for (x, y) in pts:
            emit(f"  {{ {x}, {y} }},")
        emit("};")
    emit("constexpr Landmark LANDMARKS[] = {")
    for name, lm in landmarks.items():
        ident = _c_ident(name)
        n = len(lm.get("points", []))
        emit(f"  {{ {_c_str(name)}, {_c_str(lm['color'])}, "
             f"LANDMARK_PTS_{ident}, {n} }},")
    emit("};")
    emit(f"constexpr uint16_t LANDMARK_COUNT = {len(landmarks)};")
    emit("")

    # --- agent types ---
    agents = ir.get("agents", {})
    for name, a in agents.items():
        ident = _c_ident(name)
        states = a.get("states", [])
        if states:
            emit(f"constexpr const char* AGENT_STATES_{ident}[] = {{")
            for s in states:
                emit(f"  {_c_str(s)},")
            emit("};")
    emit("constexpr AgentType AGENT_TYPES[] = {")
    for name, a in agents.items():
        ident = _c_ident(name)
        states = a.get("states", [])
        states_ref = f"AGENT_STATES_{ident}" if states else "nullptr"
        emit(f"  {{ {_c_str(name)}, {a.get('limit', 0)}, "
             f"{states_ref}, {len(states)} }},")
    emit("};")
    emit(f"constexpr uint16_t AGENT_TYPE_COUNT = {len(agents)};")
    emit("")

    # --- initial agents ---
    initial = ir.get("initial_agents", [])
    emit("constexpr InitialAgent INITIAL_AGENTS[] = {")
    for ia in initial:
        x, y = ia["pos"]
        emit(f"  {{ {_c_str(ia['name'])}, {x}, {y}, "
             f"{_c_str(ia.get('state', 'none'))} }},")
    emit("};")
    emit(f"constexpr uint16_t INITIAL_AGENT_COUNT = {len(initial)};")
    emit("")

    # --- spawn rules ---
    spawns = ir.get("spawning", [])
    emit("constexpr SpawnRule SPAWN_RULES[] = {")
    for s in spawns:
        emit(f"  {{ {_c_str(s['agent_type'])}, {_c_str(s['landmark'])}, "
             f"{s['interval']}, {_c_str(s['condition'])} }},")
    emit("};")
    emit(f"constexpr uint16_t SPAWN_RULE_COUNT = {len(spawns)};")
    emit("")

    # --- pathfinding ---
    pf = ir.get("pathfinding", {})
    top_diag = bool(pf.get("diagonal", False))
    top_cost = pf.get("diagonal_cost")
    emit(f"constexpr uint8_t PF_TOP_DIAGONAL = {1 if top_diag else 0};")
    emit(f"constexpr float   PF_TOP_DIAGONAL_COST = "
         f"{float(top_cost) if top_cost is not None else 0.0}f;")
    emit(f"constexpr uint8_t PF_TOP_HAS_DIAGONAL_COST = "
         f"{1 if top_cost is not None else 0};")
    emit("")

    per = pf.get("per_agent", {})
    emit("constexpr PFConfig PF_CONFIGS[] = {")
    for agent_name, block in per.items():
        def has(k): return 1 if k in block else 0
        diag = bool(block.get("diagonal", False))
        cost = block.get("diagonal_cost")
        emit(
            f"  {{ {_c_str(agent_name)}, "
            f"{int(block.get('max_nodes', 0))}, "
            f"{int(block.get('penalty_lit', 0))}, "
            f"{int(block.get('penalty_occupied', 0))}, "
            f"{1 if diag else 0}, "
            f"{float(cost) if cost is not None else 0.0}f, "
            f"{int(block.get('step_rate', 0))}, "
            f"{has('max_nodes')}, {has('penalty_lit')}, "
            f"{has('penalty_occupied')}, {has('diagonal')}, "
            f"{has('diagonal_cost')}, {has('step_rate')} }},"
        )
    emit("};")
    emit(f"constexpr uint16_t PF_CONFIG_COUNT = {len(per)};")
    emit("")

    # --- behaviors ---
    behaviors = ir.get("behaviors", {})
    for name, insns in behaviors.items():
        ident = _c_ident(name)
        emit(f"constexpr Insn BEH_{ident}[] = {{")
        for indent, text in insns:
            emit(f"  {{ {indent}, {_c_str(text)} }},")
        emit("};")
    emit("constexpr Behavior BEHAVIORS[] = {")
    for name, insns in behaviors.items():
        ident = _c_ident(name)
        emit(f"  {{ {_c_str(name)}, BEH_{ident}, {len(insns)} }},")
    emit("};")
    emit(f"constexpr uint16_t BEHAVIOR_COUNT = {len(behaviors)};")
    emit("")

    emit("}  // namespace critter_ir")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description="Encode a .crit IR to C++ header.")
    ap.add_argument("crit_path", help="Path to the .crit source file")
    ap.add_argument("-o", "--out", default="critter_ir.h",
                    help="Output header path (default: critter_ir.h)")
    ap.add_argument("--width",  type=int, default=16,
                    help="Grid width to substitute for max_x (default: 16)")
    ap.add_argument("--height", type=int, default=16,
                    help="Grid height to substitute for max_y (default: 16)")
    args = ap.parse_args()

    compiler = CritCompiler(width=args.width, height=args.height)
    ir = compiler.compile(args.crit_path)
    header = encode(ir, args.crit_path, args.width, args.height)
    with open(args.out, "w") as f:
        f.write(header)
    print(f"Wrote {args.out} ({len(header)} bytes)")


if __name__ == "__main__":
    main()
