"""IR encoder: compile a .crit, serialize to the OTA text wire format,
emit a C header with the blob as DEFAULT_IR_BLOB[].

Single-format principle (OTA_IR.md): the compiled-in default IR uses the
exact same bytes as an OTA-fetched blob — one parser, exercised every
boot. This file used to emit a fully-constexpr table layout; the tables
are now materialized at runtime by hal/ir/IrRuntime.cpp after it parses
the blob.

The only other things in this header are GRID_WIDTH/GRID_HEIGHT (the
engine TU doesn't see creds.h, so we plant them here) and TICK_RATE_MS
(particle main loop uses it in a constexpr context — until we make that
runtime the default tick rate has to survive as a compile-time constant).

Usage:
    python3 hal/ir/ir_encoder.py <path>.crit [-o critter_ir.h]
                                 [--width W] [--height H]
                                 [--name <script_name>]
"""

import argparse
import datetime as _dt
import hashlib
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.abspath(os.path.join(_HERE, "..", ".."))
if _REPO not in sys.path:
    sys.path.insert(0, _REPO)

from compiler import CritCompiler            # noqa: E402
from hal.ir import ir_text                   # noqa: E402


ENCODER_VERSION = "ir_encoder/2"

# Max line length we emit for the blob literal. Keeps diffs readable and
# avoids editor stalls if a human opens the generated header.
_LINE_WIDTH = 72


def _c_hex_escape(s: str) -> str:
    """Escape a Python string as a sequence of \\xHH for every byte.

    Using \\xHH-for-everything (vs mixed printable + escapes) keeps the
    output uniform and avoids C's trigraph / adjacent-digit pitfalls —
    e.g. `"abc\\x09"` adjacent to a printable `"9..."` line would be read
    as `\\x099`. All-hex sidesteps that without needing a lookahead.
    """
    out = []
    line = []
    line_len = 0
    for b in s.encode("utf-8"):
        tok = f"\\x{b:02x}"
        if line_len + len(tok) > _LINE_WIDTH:
            out.append('"' + "".join(line) + '"')
            line = []
            line_len = 0
        line.append(tok)
        line_len += len(tok)
    if line:
        out.append('"' + "".join(line) + '"')
    return "\n    ".join(out)


def encode(ir, source_path, src_text, width, height, name):
    src_sha = hashlib.sha256(src_text.encode("utf-8")).hexdigest()
    meta = {
        "name":            name,
        "src_sha256":      src_sha,
        "encoded_at":      _dt.datetime.now(_dt.timezone.utc)
                               .strftime("%Y-%m-%dT%H:%M:%SZ"),
        "encoder_version": ENCODER_VERSION,
        "ir_version":      ir.get("ir_version", 1),
        "source":          src_text,
    }
    blob = ir_text.encode(ir, meta)

    tick_rate = int(ir.get("simulation", {}).get("tick_rate", 500))

    lines = []
    lines.append("// Auto-generated by hal/ir/ir_encoder.py. Do not edit by hand.")
    lines.append(f"// Source: {os.path.basename(source_path)}")
    lines.append("#pragma once")
    lines.append("#include <cstdint>")
    lines.append("#include <cstddef>")
    lines.append("")
    # Grid geometry: CritterEngine.cpp TU doesn't see creds.h, so the
    # defines live here. #ifndef lets host builds passing -DGRID_WIDTH win.
    lines.append(f"#ifndef GRID_WIDTH")
    lines.append(f"#define GRID_WIDTH {width}")
    lines.append(f"#endif")
    lines.append(f"#ifndef GRID_HEIGHT")
    lines.append(f"#define GRID_HEIGHT {height}")
    lines.append(f"#endif")
    lines.append("")
    lines.append("namespace critter_ir {")
    lines.append("")
    # Compile-time default tick rate. The runtime-parsed blob carries its
    # own TICK value; this slot is kept for particle.cpp's constexpr main-
    # loop budgets until those go runtime.
    lines.append(f"constexpr uint32_t TICK_RATE_MS = {tick_rate};")
    lines.append("")
    # The blob itself. `inline constexpr` for C++17 header-safe definition
    # (only one TU actually includes this header today — CritterEngine.cpp
    # — but the inline keeps the door open).
    lines.append("inline constexpr char DEFAULT_IR_BLOB[] =")
    lines.append("    " + _c_hex_escape(blob) + ";")
    lines.append("")
    lines.append("inline constexpr size_t DEFAULT_IR_BLOB_LEN = "
                 f"sizeof(DEFAULT_IR_BLOB) - 1;")
    lines.append("")
    lines.append("}  // namespace critter_ir")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("crit_path", help="Path to the .crit source file")
    ap.add_argument("-o", "--out", default="critter_ir.h",
                    help="Output header path (default: critter_ir.h)")
    ap.add_argument("--width",  type=int, default=16)
    ap.add_argument("--height", type=int, default=16)
    ap.add_argument("--name", help="Script name (default: file stem)")
    args = ap.parse_args()

    name = args.name or os.path.splitext(os.path.basename(args.crit_path))[0]

    with open(args.crit_path) as f:
        src_text = f.read()
    ir = CritCompiler(width=args.width, height=args.height).compile(args.crit_path)
    header = encode(ir, args.crit_path, src_text, args.width, args.height, name)
    with open(args.out, "w") as f:
        f.write(header)
    print(f"Wrote {args.out} ({len(header)} bytes)")


if __name__ == "__main__":
    main()
