#pragma once
// Generated by `coati codegen` — DO NOT EDIT MANUALLY
// Script: aphid  Grid: 16×16

#include "Particle.h"
#include "neopixel.h"
#include <vector>
#include <queue>
#include <cmath>
#include <algorithm>
#include <cstring>
#include <cstdlib>

#define PHYSICS_TICK_MS 500
#define RENDER_TICK_MS 16

static constexpr int GRID_WIDTH = 16;
static constexpr int GRID_HEIGHT = 16;

struct Point {
    int x, y;
    bool operator==(const Point& o) const { return x == o.x && y == o.y; }
    bool operator!=(const Point& o) const { return x != o.x || y != o.y; }
};

struct AgentState {
    int   index        = 0;
    Point pos          = {0, 0};
    Point last_pos     = {0, 0};
    bool  active       = false;
    std::vector<Point> path;
    Point claimed      = {-1, -1};
    int   wait_counter = 0;
    int    pause_counter      = 0;
    int    role               = 0;
};

class CoatiEngine {
public:
    bool  current_board[GRID_WIDTH][GRID_HEIGHT] = {false};
    bool  target_board[GRID_WIDTH][GRID_HEIGHT]  = {false};
    float fade_board[GRID_WIDTH][GRID_HEIGHT]    = {0.0f};

    bool          pending_target[GRID_WIDTH][GRID_HEIGHT] = {false};
    volatile bool target_pending = false;
    time_t        active_target  = 0;
    time_t        pending_time   = 0;

    std::vector<AgentState> agents;

    std::vector<Point> tk_extras;
    std::vector<Point> tk_missing;

    static const int   nest_count;
    static const Point nest[];

    CoatiEngine();
    void tick();
    void update_target(time_t virtual_now);
    void apply_pending_target();
    void render(Adafruit_NeoPixel& strip, float bri, uint32_t now_ms, float blend, int rotation = 0);

    std::vector<Point> find_path(Point start, Point dest, int self_idx);

private:
    bool  pf_visited[GRID_WIDTH][GRID_HEIGHT];
    Point pf_parent[GRID_WIDTH][GRID_HEIGHT];
    float pf_cost[GRID_WIDTH][GRID_HEIGHT];

    Point _find_closest(Point start, const std::vector<Point>& cands);
    bool  _in_vec(const std::vector<Point>& v, Point p) const;
    bool  _near_lit(Point p) const;
    bool  _is_landmark(Point p) const;
    void  _draw_digit(int x, int y_off, char c);
};